#!/usr/bin/perl

sub writeFileCustom
{
	my $self = shift;
	
	$self->encodeFileNames();
	use Data::Dumper;
	warn Dumper($self->{tree});
	my $file = "/tmp/file.xml";
	open(FH, ">/tmp/file.xml");
	print FH <<EOF;
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- generated by Cobalt Migration Utility version 2.16 -->

  <archive>
	<cmuVersion value = "2.16"/>
	<private>
		<md5sum value = "$self->{tree}->{archive}->{private}->{md5sum}"/>
		<base value = "$self->{tree}->{archive}->{private}->{base}"/>
EOF
	foreach my $f (@{ $self->{tree}->{archive}->{private}->{file} }) {
		print FH qq/\t\t<file name = "$f->{name}" uid = "$f->{uid}" gid = "$f->{gid}"\/>\n/;
	}

	print FH <<EOF;
	</private>
	<public>
		<md5sum value = "$self->{tree}->{archive}->{public}->{md5sum}"/>
		<base value = "$self->{tree}->{archive}->{public}->{base}"/>
EOF

	foreach my $f (@{ $self->{tree}->{archive}->{public}->{file} }) {
		print FH qq/\t\t<file name = "$f->{name}" uid = "$f->{uid}" gid = "$f->{gid}"\/>\n/;
	}

	print FH <<EOF;
	</public>
  </archive>
EOF

	close(FH);
	return 1;
}


# Copyright (c) 2003 Sun Microsystems, Inc. All  Rights Reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# -Redistribution of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
# 
# -Redistribution in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation  
# and/or other materials provided with the distribution.
# 
# Neither the name of Sun Microsystems, Inc. or the names of contributors may 
# be used to endorse or promote products derived from this software without 
# specific prior written permission.
# 
# This software is provided "AS IS," without a warranty of any kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED. SUN MICROSYSTEMS, INC. ("SUN") AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# 
# You acknowledge that  this software is not designed or intended for use in the design, construction, operation or maintenance of any nuclear facility.
