#!/usr/bin/perl -I../perl_modules
# $Id: fileXml 922 2003-07-17 15:22:40Z will $

use strict;
#use Devel::Leak;


my $fileName = "/tmp/conf.xml";

#my $tree = readXml($fileName);
readXml($fileName);

sleep 10;
exit 0;


sub passVal {
	my $t = shift;
    warn "after passVal: ", $t, "\n";
    warn `ps auxwwww | grep $$ |grep fileXml`;
}


sub readXml {
	require XML::Parser;

	my $file = shift;
#	my $parse = new XML::Parser();
	my $parse = new XML::Parser(Style => 'Tree');
	my $data;
	$data = $parse->parsefile($file);

	warn `ps auxwwww | grep $$ |grep fileXml`;
	return; 
}
