#!/usr/bin/perl 
use lib "../perl_modules";

use TreeXml;
warn "FORKED with pid", $$, "\n";
my $xml;
while (my $line = <STDIN>) {
	$xml .= $line;
}

$tree = readXmlStream($xml,0);
warn "tree: ", $tree, "\n";
print writeXml($tree);

exit;



