#!/usr/bin/perl -w -I/usr/sausalito/perl -I.

my $confdir = '/etc/httpd/conf.d';

use Sauce::Config;
use FileHandle;
use File::Copy;
use CCE;

my $cce = new CCE;
$cce->connectfd();

my ($oid) = $cce->find("System");
my ($ok, $obj) = $cce->get($oid);
my ($status, $ControlPanel) = $cce->get($oid, "ControlPanel");

my $hostname = $obj->{hostname};
my $domain = $obj->{domainname};
$hostname =~ s/\.${domain}$//;
my $fqdn = $hostname . '.' . $domain;

my $urlAdminAccess = $ControlPanel->{urlAdminAccess};
my $urlSiteadminAccess = $ControlPanel->{urlSiteadminAccess};
my $urlPersonalAccess = $ControlPanel->{urlPersonalAccess};

umask(0077);
my $stage = "$confdir/bluequartz.conf~";
open(HTTPD, "$confdir/bluequartz.conf");
unlink($stage);
sysopen(STAGE, $stage, 1|O_CREAT|O_EXCL, 0600) || die;
while(<HTTPD>) {
  if(!/^Rewrite.+$/)
  {
     print STAGE;
  }	
}

print STAGE "RewriteEngine On\n";
print STAGE "RewriteCond %{HTTP_HOST}                    ^([^:]+)\n";
print STAGE "RewriteCond %{DOCUMENT_ROOT}                !-d\n";
print STAGE "RewriteRule .*                              http://%1:444/error/forbidden.html [L,R]\n";
if($urlAdminAccess) {
   print STAGE "RewriteCond %{HTTP_HOST}                ^([^:]+)\n";
   print STAGE "RewriteRule ^/admin/?\$                  http://%1:444/login.php [L,R]\n";
}
if($urlSiteadminAccess) {
   print STAGE "RewriteCond %{HTTP_HOST}                ^([^:]+)\n";
   print STAGE "RewriteRule ^/siteadmin/?\$              http://%1:444/login.php [L,R]\n";
}
if($urlPersonalAccess) {
   print STAGE "RewriteCond %{HTTP_HOST}                ^([^:]+)\n";
   print STAGE "RewriteRule ^/personal/?\$               http://%1:444/login.php [L,R]\n";
}
if($urlLoginAccess) {
   print STAGE "RewriteCond %{HTTP_HOST}                ^([^:]+)\n";
   print STAGE "RewriteRule ^/login/?\$                 	http://%1:444/login.php [L,R]\n";
}

close(STAGE);
close(HTTPD);


chmod(0644, $stage);
if(-s $stage) {
  move($stage,"$confdir/bluequartz.conf");
  chmod(0644, "$confdir/bluequartz.conf"); # paranoia
  $cce->bye("SUCCESS");
} else {
  $cce->bye("FAILURE");
}

exit(0);

