#!/usr/bin/perl
# $Id: testIn 922 2003-07-17 15:22:40Z will $

use lib "/home/cpr/perl_modules";


use TreeXml;

my $DEBUG = 1;

my $fileName = '/tmp/cmu.xml';

my $tree = readXml($fileName, 0, 0 );

warn "START\n";
foreach my $key (keys %{$tree}) {
	print "main: $key => ", $tree->{$key}, "\n";
	#warn "is: ", @{$tree->{$key}}[0]->{userName}, "\n";
	#warn "is: ", @{$tree->{$key}}[0]->{groupName}, "\n";
}
warn "Tree is: ", $tree, "\n";
my $type = "user";

warn "hash: ", %{ $tree->{$type} }, "\n";


foreach my $user (keys %{ $tree->{$type} }) {
	warn "START\n";
	#warn "en: ", $user, " => ", @{$tree->{$type}}[$user], "\n";
	my $luser = ${ $tree->{$type} }{$user};
	foreach my $key (keys %{$luser}) {
		print $key, " => ", $luser->{$key}, "\n";
	}
	
	warn "END\n";

}


