#!/usr/bin/perl -w -I/usr/sausalito/perl -I. -I/usr/sausalito/handlers/base/maillist
# $Id: listmod_members 201 2003-07-18 19:11:07Z will $
#
# listmod_members depends on:
#		name
#		local_recips
#		remote_recips
#		_CREATE

use MailList; # should be a local file
use CCE;
my $cce = new CCE;
$cce->connectfd();

my $DEBUG = 0;
$DEBUG && warn `date`;

my $oid = $cce->event_oid();
my $obj = $cce->event_object();

# hack to make sure all subscriber email addresses include @fqdn, so 
# it is harder to spoof yourself.  This may or may not break the qube, but
# oh well, the qube suffers from this problem as well.
MailList::munge_members($cce, $obj);

# create subscriber list:
MailList::rewrite_members($obj);

$cce->bye('SUCCESS');
exit(0);

