# Makefile
# $Id: Makefile 1413 2010-03-10 14:28:36Z shibuya $

VENDOR=base
VENDORNAME=cobalt
SERVICE=firewall

VERSION=1.1.0
RELEASE=24BQ7

BUILDARCH=noarch

BUILDUI=yes
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=no

INSTALL=install
INSTALL_BIN=$(INSTALL) -m 755
INSTALL_OTH=$(INSTALL) -m 644
TMPDIR=/tmp


include /usr/sausalito/devel/module.mk

