#!/usr/bin/perl
$|=1;
system("date > /tmp/tmp.txt");
print STDERR "hello!\n";

my $header = <>;
$_ = <>;
my ($oid) = m/OBJECT (\d+)/;

sleep (1);

print "get $oid\n";

sleep(1);

print "BYE SUCCESS\n";

@data = <>;
print STDERR @data;
print STDERR "Bye!\n";
