# $Id: Makefile 229 2003-07-18 20:22:20Z will $
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.

DIRMK_SRCS = \
	classconf_types.c \
	classconf_property.c \
	classconf_index.c \
	classconf_rule.c \
	classconf_matchtype.c \
	classconf_class.c \
	classconf_global.c \
	classconf_init.c \

include ../../dynamic.mk
include $(CCE_TOPDIR)/dirmake.mk

