#!/usr/bin/perl -I/usr/sausalito/perl
# $Id: ccetest,v 1.1 2001/08/20 19:24:31 jeffb Exp $
# Copyright (c) 1999,2000 Cobalt Networks, Inc. 
# http://www.cobalt.com/
#
# I use this the test specfic code here, it gets hacked and rehacked

#use lib qw(/usr/sausalito/perl);
use lib "/home/cce-shell-tools";
#use strict;

require Shell;

my $cce = new Shell;
$cce->connectuds();


my $name = $cce->getNames("User");
warn "name: ", $name, "\n";

$cce->bye("later");

