#!/bin/bash
# Author: Brian N. Smith & Michael Stauber
# Copyright 2009 Team BlueOnyx. All rights reserved.
# Small whacky shell script to build the RPM and SRPM
# Not bothering with a Makefile for now ...

MPATH=`pwd`

echo -n "Taring Up "
/bin/rm -f blueonyx-dnsImport.tar.gz
/bin/rm -f *.rpm
rm -f /usr/src/redhat/RPMS/i386/blueonyx-dnsImport-*.rpm
rm -f /usr/src/redhat/SRPMS/blueonyx-dnsImport-*.src.rpm 
/bin/tar cfpz blueonyx-dnsImport.tar.gz blueonyx-dnsImport/ blueonyx-dnsImport.spec 

echo -n "[ "; echo -en "\\033[1;36mOK\\033[0;39m"; echo " ]"

echo -n "Building new RPM "
rpmbuild -ta blueonyx-dnsImport.tar.gz >/dev/null 2>&1
echo -n "[ "; echo -en "\\033[1;36mOK\\033[0;39m"; echo " ]"
rm -f blueonyx-dnsImport.tar.gz >/dev/null 2>&1

echo -n "Moving new RPMs"

cp /usr/src/redhat/RPMS/i386/blueonyx-dnsImport-*.i386.rpm $MPATH 
cp /usr/src/redhat/SRPMS/blueonyx-dnsImport-*.src.rpm $MPATH
echo -n "[ "; echo -en "\\033[1;36mOK\\033[0;39m"; echo " ]"
echo
