# Makefile
# $Id: Makefile 201 2003-07-18 19:11:07Z will $

VENDOR=base
VENDORNAME=cobalt
SERVICE=firewall

VERSION=1.0.1
RELEASE=23

BUILDARCH=noarch

BUILDUI=yes
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=no

INSTALL=install
INSTALL_BIN=$(INSTALL) -m 755
INSTALL_OTH=$(INSTALL) -m 644
TMPDIR=/tmp


include /usr/sausalito/devel/module.mk

