#!/usr/bin/perl

use lib qw( /usr/sausalito/perl );
use CCE;
my $cce = new CCE; $cce->connectfd();

my $obj = $cce->event_object();
my $old = $cce->event_old();

my $name = $obj->{name} || $old->{name};

if ($cce->event_is_create()) {
  print STDERR "BETA: creating $name\n";
}
if ($cce->event_is_modify()) {
  print STDERR "BETA: modifying $name\n";
}
if ($cce->event_is_destroy()) {
  if ($name =~ m/immortal/i) {
	$cce->warn("This object ($name) is immortal.");
	$cce->bye("FAIL");
	exit(1);
  }
  print STDERR "BETA: destroying $name\n";
}

$cce->bye("SUCCESS");
exit(0);
