# Makefile
# $Id: Makefile 1021 2007-06-25 15:30:29Z shibuya $

VENDOR=base
VENDORNAME=cobalt
SERVICE=firewall

VERSION=1.0.1
RELEASE=24BQ4

BUILDARCH=noarch

BUILDUI=yes
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=no

INSTALL=install
INSTALL_BIN=$(INSTALL) -m 755
INSTALL_OTH=$(INSTALL) -m 644
TMPDIR=/tmp


include /usr/sausalito/devel/module.mk

