#!/usr/bin/perl
#
# chain_destroy -- garbage collects unused rules.

use lib qw( /usr/sausalito/perl );
use CCE;
$cce = new CCE;
$cce->connectfd(\*STDIN,\*STDOUT);

my $oid = $cce->event_oid();

my (@chains) = $cce->find("FirewallChain");
my (@rules) = $cce->find("FirewallRule");
my (%gc) = map { $_ => 1 } @rules; # rules to garbage collect.

foreach my $chain_oid (@chains) {
  my ($ok, $ch) = $cce->get($chain_oid);
  next if (!$ok);
  my @r = CCE->scalar_to_array($ch->{rules});
  foreach my $r (@r) {
    delete $gc{$r};
  }
}

foreach my $r_oid (keys %gc) {
  # delete these rules:
  $cce->destroy($r_oid);
}

{
  my (@oids) = $cce->find("System");
  $cce->set($oids[0], "Firewall", { 'dirty' => 1 });
}

$cce->bye("SUCCESS");


