#!/usr/bin/perl -w -I/usr/sausalito/perl -I. -I/usr/sausalito/handlers/base/maillist
# $Id: listmod_config 576 2005-09-05 10:26:24Z shibuya $
#
# depends on:
#		name
#		moderator
#     	      	postPolicy subPolicy
#		_CREATE

use MailList; # should be a local file
use CCE;
my $cce = new CCE;
$cce->connectfd();

my $oid = $cce->event_oid();
my $obj = $cce->event_object();

# hack to make spoofing a membership to a private list harder
# make sure the moderator email is of the form user@fqdn
MailList::munge_members($cce, $obj);

# create subscriber list:
MailList::rewrite_config($cce, $obj);

$cce->bye('SUCCESS');
exit(0);

