#!/usr/bin/perl -w -I/usr/sausalito/perl -I.
# $Id: 10select_spanish 259 2004-01-03 06:28:40Z shibuya $
# Sets locale auto-negotiation order

use POSIX;
use I18n;

my $ret = I18n::i18n_setSystemLocale('es');
exit $ret;

