# specify the following variables:
VENDOR=base

# if the VENDOR field is an alias, this should be the real name.
# otherwise, set it to VENDOR.
VENDORNAME='Project BlueOnyx'
SERVICE=memcache

VERSION=1.0.0
RELEASE=0BX04

# add a buildarch if desired
BUILDARCH=noarch

# locale exclude pattern
#XLOCALEPAT=

BUILDUI=new
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=no

REQUIRES=base-alpine-capstone >= 1.1-1BX52, base-vsite-ui >= 4.0-0BX36

include /usr/sausalito/devel/module.mk
