# specify the following variables:
VENDOR=base

# if the VENDOR field is an alias, this should be the real name.
# otherwise, set it to VENDOR.
VENDORNAME='Project BlueQuartz'
SERVICE=virtual

VERSION=1.0.0
RELEASE=0BQ2

# add a buildarch if desired
BUILDARCH=noarch

# locale exclude pattern
#XLOCALEPAT=

BUILDUI=no
BUILDGLUE=no
BUILDLOCALE=no
BUILDSRC=no

REQUIRES=base-bluequartz-glue

include /usr/sausalito/devel/module.mk
