# $Id: Makefile 259 2004-01-03 06:28:40Z shibuya $
# Copyright 2001 Sun Microsystems, Inc.  All rights reserved.
include ../../../dynamic.mk

CCEPHPCLASSDIR=$(CCE_INSTALLDIR)/ui/libPhp

install:
	-mkdir -p $(CCEPHPCLASSDIR)
	$(INSTALL) $(INST_BINFLAGS) CceClient.php $(CCEPHPCLASSDIR)
	$(INSTALL) $(INST_BINFLAGS) CceError.php $(CCEPHPCLASSDIR)
