# Makefile
# $Id: Makefile 1092 2008-02-05 20:24:40Z mstauber $

VENDOR=base
VENDORNAME=cobalt
SERVICE=firewall

VERSION=1.0.1
RELEASE=24BQ6

BUILDARCH=noarch

BUILDUI=yes
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=no

INSTALL=install
INSTALL_BIN=$(INSTALL) -m 755
INSTALL_OTH=$(INSTALL) -m 644
TMPDIR=/tmp


include /usr/sausalito/devel/module.mk

