#!/bin/sh
# $Id: bluequartz 697 2006-03-02 10:34:53Z shibuya $
# Copyright 2005 Project BlueQuartz.  All rights reserved.
#
# bluequartz    initianlize BlueQuartz system at first boot.
#
# chkconfig: 2345 0 0
# description: initialize BlueQuartz settings.
#

# Source function library.
. /etc/rc.d/init.d/functions

(cd /usr/sausalito/runonce
for FILE in *; do
  if [ ! "$FILE" = "*" ] && [ -h $FILE ] ; then
    echo Run Once: $FILE
    /usr/sausalito/runonce/$FILE
    rm -f /usr/sausalito/runonce/$FILE
    action "" /bin/true
  fi
done
)

exit 0

