#!/usr/bin/perl
# $Id: beta_handler 229 2003-07-18 20:22:20Z will $
# Copyright 2001 Sun Microsystems, Inc.  All rights reserved.

use lib qw( ../../../../client/perl );
use CCE;
my $cce = new CCE; $cce->connectfd();

my $obj = $cce->event_object();
my $old = $cce->event_old();

my $name = $obj->{name} || $old->{name};

print STDERR "BETA names: $obj->{name} - $old->{name}\n";

if ($cce->event_is_create()) {
  print STDERR "BETA: creating $name\n";
}
if ($cce->event_is_modify()) {
  print STDERR "BETA: modifying $name\n";
}
if ($cce->event_is_destroy()) {
  if ($name =~ m/immortal/i) {
	$cce->warn("This object ($name) is immortal.");
	$cce->bye("FAIL");
	exit(1);
  }
  print STDERR "BETA: destroying $name\n";
}

if ( ($cce->event_is_create() && $name eq 'beta-fail-on-create')
     || ($cce->event_is_modify() && $name eq 'beta-fail-on-modify')
     || ($cce->event_is_destroy() && $name eq 'beta-fail-on-destroy')
) {
	$cce->bye("FAIL"); exit(1);
}

$cce->bye("SUCCESS");
exit(0);
