#!/usr/bin/perl

use lib qw( /usr/sausalito/perl );
use CCE;
use Time::HiRes qw ( gettimeofday tv_interval );
my $cce = new CCE;
$cce->connectuds();

my $t= time();

my @dur = ();
for (my $i = 0; $i < 500; $i++) {
	my $t0 = [gettimeofday];
	$cce->create("Beta", { 'name' => $t . ".$i", "foo" => $i });
	my $d = tv_interval($t0, [gettimeofday]);
	print STDERR "$d\n";
	push (@dur, $d);
}


