#!/usr/bin/perl
# $Id: gamma_handler 259 2004-01-03 06:28:40Z shibuya $
# Copyright 2001 Sun Microsystems, Inc.  All rights reserved.

$| = 1;

while(<>)
{
	print STDERR $_;
	if (/^200 READY/)
	{
		last;
	}
}

print STDERR "BADDATA 0 gamma bar\n";
print "BADDATA 0 gamma bar\n";

print STDERR "BYE FAIL\n";
print "BYE FAIL\n";

while (<>)
{
	print STDERR $_;
}

