#!/bin/sh

rm `find /usr/sausalito/ui/style/ -name "*.compiled.*"` >/dev/null 2>&1

echo "** make clean"
make clean
echo "** make"
make
echo "** make install"
make install
echo "** reload httpd, admserv, cced"
killall pperld 2>/dev/null
/usr/sausalito/sbin/cced.init reload
/sbin/service admserv reload
/sbin/service httpd reload
echo ""
echo "** Fin"
