#!/usr/bin/perl

# MODULE: base-ftp.mod:DEV_4000WGML:ui,locale,glue,capstone,src
# MODULE: base-import.mod:DEV_4000WGML:ui,glue,locale,capstone,capstone
# MODULE: base-ldap.mod:DEV_4000WGML:ui,locale,glue,capstone
# MODULE: base-maillist.mod:DEV_4000WGML:ui,locale,glue,capstone
# MODULE: base-modem.mod:DEV_4000WGML:locale,glue,capstone,ui

my $basedir = $ARGV[0];
$basedir ||= $ENV{'BUILDDIR'};
$basedir ||= '/home/dev';

system('mkdir', '-p', $basedir) unless (-d $basedir); 


open(LIST, "packing_list") || die "Could not open packing list";

chdir($basedir) || die "Could not access directory $basedir: $!";

while(<LIST>)
{
	next unless (/^MODULE:\s/);
	$_ =~ s/^MODULE:\s+//g;

	my @goods = split(':');
	my @command = ('cvs', 'co');
	push(@command, '-r', $goods[1]) if ($goods[1] && ($goods[1] ne 'HEAD'));

	system(@command, $goods[0]);
}

exit 0;
