#!/usr/bin/perl 

use Archive::Tar;

my @ig = ("_vti",".forward",".vacation_msg");
my $file = "/tmp/test.tar";
my $dir = "/tmp/test";
my $tar = Archive::Tar->new();

chdir "$dir" || die " wtf?\n";
$tar->extract_archive($file);


