# specify the following variables:
VENDOR=base

# if the VENDOR field is an alias, this should be the real name.
# otherwise, set it to VENDOR.
VENDORNAME='Team BlueOnyx'
SERVICE=java

VERSION=2.0.6
RELEASE=10

# add a buildarch if desired
BUILDARCH=noarch

# locale exclude pattern
#XLOCALEPAT=

BUILDUI=yes
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=yes

REQUIRES= base-java-am base-java-filler jpackage-utils ant axis bcel chkfontpath classpathx-jaf classpathx-mail cryptix cryptix-asn1 jakarta-commons-beanutils jakarta-commons-collections jakarta-commons-dbcp jakarta-commons-digester jakarta-commons-discovery jakarta-commons-el jakarta-commons-fileupload jakarta-commons-httpclient3 jakarta-commons-launcher jakarta-commons-logging jakarta-commons-modeler jakarta-commons-pool jakarta-commons-validator jakarta-taglibs-standard jta log4j mod_jk-ap20 mx4j oro puretls regexp saxon struts tomcat5 tomcat5-admin-webapps tomcat5-jasper tomcat5-servlet-2.4-api tomcat5-webapps unixODBC unixODBC-devel wsdl4j xerces-j2 xml-commons xml-commons-apis xml-commons-resolver xorg-x11-deprecated-libs xorg-x11-font-utils xorg-x11-xfs java-1.6.0-sun java-1.6.0-sun-devel java-1.6.0-sun-fonts java-1.6.0-sun-jdbc 

#########
# some useful defines
INSTALL=install
INSTALL_BIN=$(INSTALL) -m 755
INSTALL_OTH=$(INSTALL) -m 644
TMPDIR=/tmp

include /usr/sausalito/devel/module.mk
