#!/usr/bin/perl 

use lib "../perl_modules";
require CmuCfg;

my $cfg = CmuCfg->new(type => 'scanout');
#require Getopt::Std;
#Getopt::Std::getopts('acd:f:ghi:n:p', $cfg->{opts});
$cfg->parseOpts();

#my $new = $cfg->mapOpts();

#if($cfg->isOpt('g')) { 
#	print "read\n";
#	$cfg->addGlbConf();
#} else {
#	print "read from stdin\n";
#}
use Data::Dumper;
warn Dumper($cfg);
