# $Id: Makefile 259 2004-01-03 06:28:40Z shibuya $
# Copyright 2001 Sun Microsystems, Inc.  All rights reserved.

test:
	make -C alphabeta test
	make -C baddata test
	make -C sorting test
#	maje -C magic_props test
#	make -C security test

clean:
	make -C alphabeta clean
	make -C baddata clean
	make -C sorting clean
#	maje -C magic_props clean
#	make -C security clean
