# specify the following variables:
VENDOR=base

# if the VENDOR field is an alias, this should be the real name.
# otherwise, set it to VENDOR.
VENDORNAME=cobalt
SERVICE=sys

VERSION=1.0.1
RELEASE=54

# add a buildarch if desired
BUILDARCH=noarch

# locale exclude pattern
#XLOCALEPAT=

BUILDUI=no
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=yes

include /usr/sausalito/devel/module.mk
