#!/bin/sh
# $Id: blueonyx Wed Jun 02 2010  mstauber $
# Copyright 2005-2010 Project BlueOnyx.  All rights reserved.
#
# blueonyx - initializes BlueOnyx system at first boot.
#
# chkconfig: 2345 0 0
# description: initialize BlueOnyx settings.
#

# Source function library.
. /etc/rc.d/init.d/functions

(cd /usr/sausalito/runonce
for FILE in *; do
  if [ ! "$FILE" = "*" ] && [ -h $FILE ] ; then
    echo Run Once: $FILE
    /usr/sausalito/runonce/$FILE
    rm -f /usr/sausalito/runonce/$FILE
    action "" /bin/true
  fi
done
)

exit 0

