#!/usr/bin/perl
# $Id: alphabeta_handler 229 2003-07-18 20:22:20Z will $
# Copyright 2001 Sun Microsystems, Inc.  All rights reserved.

$| = 1;

# sleep half a second.  we need the output to be ordered.
sleep 0.5;

while(<>)
{
	print STDERR "alphahandler: ", $_;
	if (/^200 READY/)
	{
		last;
	}
}

print STDERR "alphahandler: ", "SET 2 name=bar\n";
print "SET 2 name=bar\n";

while (<>)
{
	print STDERR "alphahandler: ", $_;
	if (/^4/ || /^2/)
	{
		last;
	}
}

print STDERR "alphahandler: ", "BADDATA 1 alpha bar\n";
print "BADDATA 1 alpha bar\n";

print STDERR "alphahandler: ", "BYE FAIL\n";
print "BYE FAIL\n";

while (<>)
{
	print STDERR "alphahandler: ", $_;
}

