# Makefile
# $Id: Makefile 3 2003-07-17 15:19:15Z will $

VENDOR=base
VENDORNAME=cobalt
SERVICE=firewall

VERSION=1.0.1
RELEASE=19

BUILDARCH=noarch

BUILDUI=yes
BUILDGLUE=yes
BUILDLOCALE=yes
BUILDSRC=no

INSTALL=install
INSTALL_BIN=$(INSTALL) -m 755
INSTALL_OTH=$(INSTALL) -m 644
TMPDIR=/tmp


include /usr/sausalito/devel/module.mk

