#!/usr/bin/perl -I../perl_modules
# $Id: createBaseLine 922 2003-07-17 15:22:40Z will $

use strict;

my $addU = "/usr/sbin/cadduser";
my $addV = "/usr/sbin/caddvsite";
my $sites = {
	'www.test.com' => {
		'-i' => '172.16.77.1',
		'-q' => 20000,
		'-n' => 'www',
		'-d' => 'test.com',
		'-l' => '',
		'-t' => '',
	},
	'www.release.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'reslease.com',
		'-s' => '',
		'-t' => '',
	},
	'www.okok.com' => {
		'-i' => '172.16.77.3',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'okok.com',
		'-s' => '',
		'-t' => '',
	},
	'www.theorizer.com' => {
		'-i' => '172.16.77.4',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'theorizer.com',
		'-s' => '',
		'-t' => '',
	},
	'www.thera.com' => {
		'-i' => '172.16.77.5',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'thera.com',
		'-s' => '',
		'-t' => '',
	},
	'www.theolog.com' => {
		'-i' => '172.16.77.6',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'theolog.com',
		'-s' => '',
		'-t' => '',
	},
	'www.supplier.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'supplier.com',
		'-s' => '',
		'-t' => '',
	},
	'www.thereabout.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'thereabout.com',
		'-s' => '',
		'-t' => '',
	},
	'www.drive.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'drive.com',
		'-s' => '',
		'-t' => '',
	},
	'www.vim.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'vim.com',
		'-s' => '',
		'-t' => '',
	},
	'www.elm.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'elm.com',
		'-s' => '',
		'-t' => '',
	},
	'www.pine.com' => {
		'-i' => '172.16.77.2',
		'-q' => 1000,
		'-n' => 'www',
		'-d' => 'pine.com',
		'-s' => '',
		'-t' => '',
	},

};

my $users = {
	'jeffb' => {
		'-d' => 'www.test.com',
		'-u' => 'jeffb',
		'-q' => '250',
		'-f' => 'Jeff Bilicki',
		'-t' => '',
		'-a' => '',
	},
	'myself2' => {
		'-g' => 'site2',
		'-u' => 'myself2',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself3' => {
		'-g' => 'site3',
		'-u' => 'myself3',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},	
	'myself4' => {
		'-g' => 'site4',
		'-u' => 'myself4',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself5' => {
		'-g' => 'site5',
		'-u' => 'myself5',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself6' => {
		'-g' => 'site6',
		'-u' => 'myself6',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself7' => {
		'-g' => 'site7',
		'-u' => 'myself7',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself8' => {
		'-g' => 'site8',
		'-u' => 'myself8',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself9' => {
		'-g' => 'site9',
		'-u' => 'myself9',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself10' => {
		'-g' => 'site10',
		'-u' => 'myself10',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself11' => {
		'-g' => 'site11',
		'-u' => 'myself11',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
	'myself12' => {
		'-g' => 'site12',
		'-u' => 'myself12',
		'-q' => '200',
		'-f' => 'whoami',
		'-a' => '',
		'-t' => '',
	},
};


addVsites($sites);
addUsers($users);
exit 0;

sub addVsites
{
	my $vsites = shift;
	
	foreach my $site (keys %{ $sites }) {
		my $cmd = $addV." ";

		foreach my $opt (keys %{ $sites->{$site} }) {
			if($sites->{$site}->{$opt}) {
				$cmd .= $opt." \"".$sites->{$site}->{$opt}."\" ";
			} else { $cmd .= $opt." "; }
		}
		system("$cmd");
	}
	return;
}

sub addUsers
{
	my $users = shift;
	
	foreach my $user (keys %{ $users }) {
		my $cmd = $addU." ";
		foreach my $opt (keys %{ $users->{$user} }) {
			if($users->{$user}->{$opt}) {
				$cmd .= $opt." \"".$users->{$user}->{$opt}."\" ";
			} else { $cmd .= $opt." "; }
		}
		system("$cmd");
		my $dir;
		if($users->{$user}->{'-a'}) {
			if($users->{$user}->{'-d'}) {
			$dir = "/home/sites/".$users->{$user}->{'-d'}."/web";
			createData($dir, $users->{$user}->{'-u'});
			} elsif($users->{$user}->{'-g'}) {
			$dir = "/home/sites/".$users->{$user}->{'-g'}."/web";
			createData($dir, $users->{$user}->{'-u'});
			}
		} else {
			if($users->{$user}->{'-d'}) {
			$dir = "/home/sites/".$users->{$user}->{'-d'}."/users/".$users->{$user}->{'-u'}."/web";
			createData($dir, $users->{$user}->{'-u'});
			} elsif($users->{$user}->{'-g'}) {
			$dir = "/home/sites/".$users->{$user}->{'-g'}."/web";
			createData($dir, $users->{$user}->{'-u'});
			}
		}
		sendMail($user);
	}
	return;
}


sub createData 
{
	my $dir = shift;
	my $user = shift;

	my $src = "/home/tmp/data/*";
	my $cpCmd = "/bin/cp -R $src $dir";


	my $cmd = "su -c \"$cpCmd\" $user";
	system("$cmd");


}

sub sendMail
{
	my $name = shift || return;
	my $text = <<EOF;
	
	This is a test message you should get this!!!!!
EOF
	

	system("echo \"$text\" | mail $name");
	return;
}

