#!/bin/bash
# Author: Brian N. Smith & Michael Stauber
# Copyright 2009 Team BlueOnyx. All rights reserved.
# Small whacky shell script to build the RPM and SRPM
# Not bothering with a Makefile for now ...

MPATH=`pwd`

echo -n "Taring Up "
/bin/rm -f blueonyx-dnstoolbox.tar.gz
/bin/rm -f *.rpm
rm -f /usr/src/redhat/RPMS/noarch/blueonyx-dnstoolbox-*.rpm
rm -f /usr/src/redhat/SRPMS/blueonyx-dnstoolbox-*.src.rpm 
/bin/tar cfpz blueonyx-dnstoolbox.tar.gz blueonyx-dnstoolbox/ blueonyx-dnstoolbox.spec --exclude=.svn

echo -n "[ "; echo -en "\\033[1;36mOK\\033[0;39m"; echo " ]"

echo -n "Building new RPM "
rpmbuild -ta blueonyx-dnstoolbox.tar.gz >/dev/null 2>&1
echo -n "[ "; echo -en "\\033[1;36mOK\\033[0;39m"; echo " ]"
rm -f blueonyx-dnstoolbox.tar.gz >/dev/null 2>&1

echo -n "Moving new RPMs"

cp /usr/src/redhat/RPMS/noarch/blueonyx-dnstoolbox-*.noarch.rpm $MPATH 
cp /usr/src/redhat/SRPMS/blueonyx-dnstoolbox-*.src.rpm $MPATH
echo -n "[ "; echo -en "\\033[1;36mOK\\033[0;39m"; echo " ]"
echo
