#!/bin/bash
# $Id: fixhosts

/bin/mv /etc/hosts /etc/.hosts
/bin/sed ':start; /### Begin - Nuonce hosts Fix.*/{; :loop; N; /###  End  - Nuonce hosts Fix.*/!{; s/.*//; b loop; }; d; b start; };' /etc/.hosts > /etc/hosts
/bin/rm -f /etc/.hosts
/bin/echo "### Begin - Nuonce hosts Fix" >> /etc/hosts
ips=`ifconfig | grep inet | cut -d: -f2 | cut -d' ' -f1`
for ip in $ips; do 
  cat /etc/hosts | grep $ip >/dev/null
  /usr/bin/printf "$ip\t`hostname`\n" >> /etc/hosts
done
/bin/echo "###  End  - Nuonce hosts Fix" >> /etc/hosts
/bin/chmod 644 /etc/hosts
exit 0

# 
# Copyright (c) 2015 Team BlueOnyx, BLUEONYX.IT
# Copyright (c) 2005 Brian N. Smith, NuOnce Networks.
# All Rights Reserved.
# 
# 1. Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
#    notice, this list of conditions and the following disclaimer in 
#    the documentation and/or other materials provided with the 
#    distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its 
#    contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
# You acknowledge that this software is not designed or intended for 
# use in the design, construction, operation or maintenance of any 
# nuclear facility.
# 