#!/usr/bin/perl -I../perl_modules
# $Id: fileOut 922 2003-07-17 15:22:40Z will $

#use strict;

my $DEBUG = 1;

#test_getList();
#test_tarUser();
remapIt();


sub remapIt
{

	use Archive;
	my $obj = "jeffb";
	my $d = "/home/cmu/q98.cobalt.com";
	my $new = "fuck";

	my $ret = Archive::remapTar("user", $obj, $new);
	warn "ret: ", $ret, "\n";
	
}


sub test_tarUser
{
	use Archive;
	my $obj = "jeffb";
	my $d = "/home/cmu/test";
	
	my $ret = Archive::tarUser($obj,$d);
	warn "ret: ", $ret, "\n";



}




sub test_getList
{
	my $user = "admin";
	my $dir = "/home/users/admin";
	my $ignore = {
		".netscape" => 1,
		".stuff" => 1,
		cvs => 1
	};
	my @it = Archive::getList($user,$dir,$ignore);
	warn "count: ", scalar(@it), "\n";
	warn "files: ", @it, "\n";

	my $tree = {};
    my $archive = {};
	TreeXml::addNode('archive', $archive, $tree);
	my $files = {};
	TreeXml::addNode('files', $files, $archive);
    my @arr = Archive::getAttr($dir,@it);
	@{ $files->{file} } = @arr;

	#my %fileTree = %{$archive->{file}};
	#warn "fileTree: ", @fileTree, "\n";
	#foreach my $file (keys %fileTree) {
#		warn "file: ", $file, " => ", $fileTree{$file}, "\n";
#	}

	my @list = @{ $files->{file} };
for my $item (@list) {
    warn "name: ", $item->{name}, "\n";
    #for my $i (keys %{ $item }) {
    #   warn "file: ", $i, "=>", $item->{$i}->{value}, "\n";
    #}
}


	TreeXml::writeXml($tree,"/tmp/file.out");



}

sub node 
{
	my $fileName = 'file.xml';

	my $hash = { 
		name => "new.html",
		uid => "luser",
		size => "2345",
		mtime => "32423423",
		gid => "home",
		mode => "644"
	};

	my $base = {};
	$ret = addNode("file",$hash,$base);

	warn "ret: ", $ret, "\n";
	warn "base: ", $base, "\n";

	#for my $key (keys %{$ret}) {
	#	warn "key: ", $key, " => ", $$ret{$key}, "\n";
	#}
				
	my $files = $ret;
	my $fileTree = $base->{file};
	warn "fileTree: ", $fileTree, "\n";
	foreach my $file (keys %{$fileTree}) {
		warn "file: ", $file, " => ", $$fileTree{$file}, "\n";
	}

}
